# Generated by Django 5.0.1 on 2025-07-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('request_body', models.TextField(blank=True)),
                ('request_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField()),
                ('response_body', models.TextField(blank=True)),
                ('response_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('validation_successful', models.BooleanField(blank=True, null=True)),
                ('national_id_count', models.PositiveIntegerField(default=0, help_text='Number of IDs processed in this request')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='authentication.apikey')),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='usage_track_api_key_3ac975_idx'), models.Index(fields=['timestamp'], name='usage_track_timesta_6a1251_idx'), models.Index(fields=['endpoint', 'timestamp'], name='usage_track_endpoin_a70b1e_idx'), models.Index(fields=['ip_address', 'timestamp'], name='usage_track_ip_addr_90c6ad_idx'), models.Index(fields=['status_code', 'timestamp'], name='usage_track_status__d44431_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('total_validations', models.PositiveIntegerField(default=0)),
                ('successful_validations', models.PositiveIntegerField(default=0)),
                ('failed_validations', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('min_response_time_ms', models.FloatField(blank=True, null=True)),
                ('max_response_time_ms', models.FloatField(blank=True, null=True)),
                ('total_request_bytes', models.BigIntegerField(default=0)),
                ('total_response_bytes', models.BigIntegerField(default=0)),
                ('cache_hits', models.PositiveIntegerField(default=0)),
                ('cache_misses', models.PositiveIntegerField(default=0)),
                ('billable_units', models.PositiveIntegerField(default=0, help_text='Number of billable units (e.g., validations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='authentication.apikey')),
            ],
            options={
                'verbose_name': 'Daily Usage Summary',
                'verbose_name_plural': 'Daily Usage Summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['api_key', 'date'], name='usage_track_api_key_57ebac_idx'), models.Index(fields=['date'], name='usage_track_date_025fed_idx')],
                'unique_together': {('api_key', 'date')},
            },
        ),
    ]
